# Generated by Django 4.2.28 on 2026-02-05 16:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('categoria', models.CharField(choices=[('EX', 'Excelente'), ('RE', 'Regular'), ('MO', 'Moroso'), ('NU', 'Nuevo')], default='NU', max_length=2, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=2, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Monto Solicitado')),
                ('tasa_interes_porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Tasa de Interés (%)')),
                ('monto_total_a_pagar', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Monto Total a Pagar')),
                ('cuotas_pactadas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Cuotas')),
                ('frecuencia', models.CharField(choices=[('DI', 'Diario'), ('SE', 'Semanal'), ('QU', 'Quincenal'), ('ME', 'Mensual')], default='DI', max_length=2, verbose_name='Frecuencia de Pago')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_finalizacion', models.DateField(editable=False, null=True, verbose_name='Fecha de Finalización')),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('FI', 'Finalizado'), ('CA', 'Cancelado'), ('RE', 'Renovado')], default='AC', max_length=2, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField(verbose_name='Número de Cuota')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de Cuota')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Pagado')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado'), ('PC', 'Pago Parcial')], default='PE', max_length=2, verbose_name='Estado')),
                ('fecha_pago_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago Real')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.prestamo', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['prestamo', 'numero_cuota'],
                'unique_together': {('prestamo', 'numero_cuota')},
            },
        ),
    ]
