# Generated by Django 6.0.2 on 2026-02-05 20:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Ruta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Prioridad')),
                ('color', models.CharField(default='#0d6efd', help_text='Color en formato hexadecimal', max_length=7, verbose_name='Color')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Ruta de Cobro',
                'verbose_name_plural': 'Rutas de Cobro',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='dia_pago_preferido',
            field=models.CharField(blank=True, help_text='Ej: Lunes, Martes, etc.', max_length=20, null=True, verbose_name='Día de Pago Preferido'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Máximo que se le puede prestar a este cliente', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Límite de Crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_comercio',
            field=models.CharField(blank=True, help_text='Ej: Tienda, Venta ambulante, Empleado, etc.', max_length=100, null=True, verbose_name='Tipo de Comercio/Negocio'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='es_renovacion',
            field=models.BooleanField(default=False, help_text='Indica si este préstamo es una renovación de otro', verbose_name='Es Renovación'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='prestamo_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='core.prestamo', verbose_name='Préstamo Anterior'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.rutacobro', verbose_name='Ruta de Cobro'),
        ),
    ]
