# Generated by Django 6.0.2 on 2026-02-05 20:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rutacobro_cliente_dia_pago_preferido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnaPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_columna', models.CharField(choices=[('cliente_nombre', 'Nombre del Cliente'), ('cliente_telefono', 'Teléfono'), ('cliente_direccion', 'Dirección'), ('cliente_categoria', 'Categoría del Cliente'), ('cliente_tipo_negocio', 'Tipo de Negocio'), ('cliente_ruta', 'Ruta de Cobro'), ('cliente_dia_pago', 'Día de Pago Preferido'), ('cuota_numero', 'Número de Cuota'), ('cuota_monto', 'Monto de Cuota'), ('cuota_vencimiento', 'Fecha de Vencimiento'), ('prestamo_monto', 'Monto del Préstamo'), ('prestamo_total', 'Total a Pagar'), ('prestamo_pendiente', 'Saldo Pendiente'), ('prestamo_fecha_inicio', 'Fecha de Inicio'), ('prestamo_fecha_fin', 'Fecha Finalización Est.'), ('prestamo_frecuencia', 'Frecuencia de Pago'), ('prestamo_renovacion', 'Es Renovación'), ('prestamo_progreso', 'Progreso (%)'), ('columna_cobrado', 'Espacio para Cobrado'), ('columna_firma', 'Espacio para Firma'), ('columna_notas', 'Espacio para Notas')], max_length=50, verbose_name='Columna')),
                ('titulo_personalizado', models.CharField(blank=True, help_text='Dejar vacío para usar el título por defecto', max_length=50, null=True, verbose_name='Título Personalizado')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('ancho', models.CharField(default='auto', help_text='Ej: auto, 100px, 15%', max_length=10, verbose_name='Ancho')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Columna de Planilla',
                'verbose_name_plural': 'Columnas de Planilla',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('EX', 'Excelente'), ('RE', 'Regular'), ('MO', 'Moroso'), ('NU', 'Nuevo')], max_length=2, unique=True, verbose_name='Categoría de Cliente')),
                ('limite_maximo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto máximo que se puede prestar a esta categoría (0 = sin límite)', max_digits=12, verbose_name='Límite Máximo de Préstamo')),
                ('porcentaje_sobre_deuda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje adicional que se puede prestar sobre deuda actual. Ej: 50 = hasta 50% más de lo que debe', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('500.00'))], verbose_name='% Adicional sobre Deuda')),
                ('puede_renovar_con_deuda', models.BooleanField(default=True, help_text='Si puede renovar préstamos con saldo pendiente', verbose_name='Puede Renovar con Deuda')),
                ('dias_minimos_para_renovar', models.PositiveIntegerField(default=0, help_text='Días mínimos que debe haber pagado antes de renovar (0 = sin restricción)', verbose_name='Días Mínimos para Renovar')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Configuración de Crédito',
                'verbose_name_plural': 'Configuraciones de Crédito',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='TipoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('limite_credito_sugerido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Límite sugerido para este tipo de negocio (0 = sin límite)', max_digits=12, verbose_name='Límite de Crédito Sugerido')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tipo de Negocio',
                'verbose_name_plural': 'Tipos de Negocio',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_comercio',
            field=models.CharField(blank=True, help_text='Campo de texto libre (usar Tipo Negocio para categorías)', max_length=100, null=True, verbose_name='Tipo de Comercio/Negocio (texto)'),
        ),
        migrations.CreateModel(
            name='ConfiguracionPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Planilla Principal', max_length=100, verbose_name='Nombre')),
                ('titulo_reporte', models.CharField(default='PLANILLA DE COBROS', max_length=200, verbose_name='Título del Reporte')),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo')),
                ('mostrar_logo', models.BooleanField(default=True, verbose_name='Mostrar Logo')),
                ('mostrar_fecha', models.BooleanField(default=True, verbose_name='Mostrar Fecha')),
                ('mostrar_totales', models.BooleanField(default=True, verbose_name='Mostrar Totales')),
                ('mostrar_firmas', models.BooleanField(default=True, verbose_name='Mostrar Espacio para Firmas')),
                ('agrupar_por_ruta', models.BooleanField(default=True, verbose_name='Agrupar por Ruta')),
                ('agrupar_por_categoria', models.BooleanField(default=False, verbose_name='Agrupar por Categoría')),
                ('incluir_vencidas', models.BooleanField(default=True, verbose_name='Incluir Cuotas Vencidas')),
                ('es_default', models.BooleanField(default=False, verbose_name='Es Configuración por Defecto')),
                ('filtrar_por_ruta', models.ForeignKey(blank=True, help_text='Dejar vacío para mostrar todas las rutas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rutacobro', verbose_name='Filtrar por Ruta')),
            ],
            options={
                'verbose_name': 'Configuración de Planilla',
                'verbose_name_plural': 'Configuraciones de Planilla',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_negocio',
            field=models.ForeignKey(blank=True, help_text='Categoría de negocio administrable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.tiponegocio', verbose_name='Tipo de Negocio'),
        ),
    ]
