# Generated by Django 6.0.2 on 2026-02-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_columnaplanilla_configuracioncredito_tiponegocio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnaplanilla',
            name='nombre_columna',
            field=models.CharField(choices=[('numero', '# (Número de fila)'), ('nombre_cliente', 'Nombre del Cliente'), ('telefono', 'Teléfono'), ('direccion', 'Dirección'), ('categoria', 'Categoría del Cliente'), ('tipo_negocio', 'Tipo de Negocio'), ('ruta', 'Ruta de Cobro'), ('dia_pago', 'Día de Pago Preferido'), ('cuota_actual', 'Número de Cuota (X/N)'), ('monto_cuota', 'Monto de Cuota'), ('fecha_vencimiento', 'Fecha de Vencimiento'), ('monto_solicitado', 'Monto Solicitado'), ('monto_total', 'Total a Pagar'), ('monto_pendiente', 'Saldo Pendiente'), ('fecha_fin_prestamo', 'Fecha Finalización Est.'), ('es_renovacion', 'Es Renovación'), ('espacio_cobrado', 'Espacio para Cobrado'), ('espacio_firma', 'Espacio para Firma'), ('espacio_notas', 'Espacio para Notas')], max_length=50, verbose_name='Columna'),
        ),
    ]
