# Generated by Django 4.2.27 on 2026-02-10 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_columnaplanilla_nombre_columna'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Respaldo Automático', max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('frecuencia_horas', models.PositiveIntegerField(default=24, help_text='Cada cuántas horas hacer respaldo', verbose_name='Frecuencia (horas)')),
                ('ruta_destino', models.CharField(default='backups/', help_text='Carpeta donde se guardarán los respaldos', max_length=500, verbose_name='Ruta de Destino')),
                ('mantener_ultimos', models.PositiveIntegerField(default=7, help_text='Cantidad de respaldos a mantener (los más antiguos se eliminan)', verbose_name='Mantener Últimos')),
                ('ultimo_respaldo', models.DateTimeField(blank=True, null=True, verbose_name='Último Respaldo')),
                ('incluir_media', models.BooleanField(default=False, verbose_name='Incluir Archivos Media')),
            ],
            options={
                'verbose_name': 'Configuración de Respaldo',
                'verbose_name_plural': 'Configuraciones de Respaldo',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CV', 'Cuota Vencida'), ('CP', 'Cuota por Vencer'), ('PF', 'Préstamo Finalizado'), ('CM', 'Cliente Moroso'), ('CR', 'Cobro Realizado'), ('RN', 'Renovación'), ('AS', 'Alerta del Sistema'), ('IN', 'Información')], max_length=2, verbose_name='Tipo')),
                ('prioridad', models.CharField(choices=[('AL', 'Alta'), ('ME', 'Media'), ('BA', 'Baja')], default='ME', max_length=2, verbose_name='Prioridad')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('enlace', models.CharField(blank=True, help_text='URL para redireccionar al hacer clic', max_length=500, null=True, verbose_name='Enlace')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario destinatario. Si es null, es para todos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('CR', 'Crear'), ('ED', 'Editar'), ('EL', 'Eliminar'), ('CO', 'Cobro'), ('RE', 'Renovación'), ('LO', 'Inicio de Sesión'), ('LU', 'Cierre de Sesión'), ('CE', 'Cambio de Estado'), ('RS', 'Respaldo'), ('OT', 'Otro')], max_length=2, verbose_name='Tipo de Acción')),
                ('tipo_modelo', models.CharField(choices=[('CL', 'Cliente'), ('PR', 'Préstamo'), ('CU', 'Cuota'), ('US', 'Usuario'), ('CF', 'Configuración'), ('SI', 'Sistema')], max_length=2, verbose_name='Tipo de Modelo')),
                ('modelo_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Registro')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('datos_anteriores', models.TextField(blank=True, help_text='JSON con los datos antes del cambio', null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.TextField(blank=True, help_text='JSON con los datos después del cambio', null=True, verbose_name='Datos Nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='core_regist_fecha_h_7dc1b2_idx'), models.Index(fields=['tipo_accion'], name='core_regist_tipo_ac_f07a6b_idx'), models.Index(fields=['usuario'], name='core_regist_usuario_3ed479_idx'), models.Index(fields=['tipo_modelo', 'modelo_id'], name='core_regist_tipo_mo_4ada87_idx')],
            },
        ),
    ]
