# Generated by Django 4.2.27 on 2026-02-12 10:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_usuario_to_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Principal', max_length=100, verbose_name='Nombre')),
                ('porcentaje_diario', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Porcentaje de interés que se aplica por cada día de mora', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje Diario (%)')),
                ('dias_gracia', models.PositiveIntegerField(default=0, help_text='Días después del vencimiento sin aplicar interés', verbose_name='Días de Gracia')),
                ('aplicar_automaticamente', models.BooleanField(default=True, help_text='Calcular intereses automáticamente al registrar pagos', verbose_name='Aplicar Automáticamente')),
                ('monto_minimo_mora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto mínimo para cobrar interés por mora (0 = sin mínimo)', max_digits=12, verbose_name='Monto Mínimo de Mora')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Configuración de Mora',
                'verbose_name_plural': 'Configuraciones de Mora',
            },
        ),
        migrations.AddField(
            model_name='cuota',
            name='interes_mora_cobrado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Interés por Mora Cobrado'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EF', 'Efectivo'), ('TR', 'Transferencia'), ('MX', 'Mixto')], default='EF', max_length=2, null=True, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='monto_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Monto en Efectivo'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='monto_transferencia',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Monto en Transferencia'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='referencia_transferencia',
            field=models.CharField(blank=True, help_text='Número de operación o referencia bancaria', max_length=100, null=True, verbose_name='Referencia de Transferencia'),
        ),
        migrations.CreateModel(
            name='InteresMora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('dias_mora', models.PositiveIntegerField(verbose_name='Días de Mora')),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje Aplicado')),
                ('monto_base', models.DecimalField(decimal_places=2, help_text='Monto sobre el cual se calculó el interés', max_digits=12, verbose_name='Monto Base')),
                ('monto_interes', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de Interés')),
                ('agregado_manualmente', models.BooleanField(default=False, verbose_name='Agregado Manualmente')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses_mora', to='core.cuota', verbose_name='Cuota')),
            ],
            options={
                'verbose_name': 'Interés por Mora',
                'verbose_name_plural': 'Intereses por Mora',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
