# Generated by Django 4.2.27 on 2026-02-15 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_configuracionmora_cuota_interes_mora_cobrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que gestiona este cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario/Cobrador'),
        ),
        migrations.AlterField(
            model_name='columnaplanilla',
            name='nombre_columna',
            field=models.CharField(choices=[('numero', '# (Número de fila)'), ('nombre_cliente', 'Nombre del Cliente'), ('telefono', 'Teléfono'), ('direccion', 'Dirección'), ('categoria', 'Categoría del Cliente'), ('tipo_negocio', 'Tipo de Negocio'), ('ruta', 'Ruta de Cobro'), ('dia_pago', 'Día de Pago Preferido'), ('cuota_actual', 'Número de Cuota (X/N)'), ('monto_cuota', 'Monto de Cuota'), ('fecha_vencimiento', 'Fecha de Vencimiento'), ('fecha_cobro', 'Fecha de Cobro'), ('monto_solicitado', 'Monto Solicitado'), ('monto_total', 'Total a Pagar'), ('monto_pendiente', 'Saldo Pendiente'), ('fecha_fin_prestamo', 'Fecha Finalización Est.'), ('prestamo_pagado', 'Préstamo Pagado'), ('es_renovacion', 'Es Renovación'), ('espacio_cobrado', 'Espacio para Cobrado'), ('espacio_firma', 'Espacio para Firma'), ('espacio_notas', 'Espacio para Notas')], max_length=50, verbose_name='Columna'),
        ),
    ]
