# Generated by Django 6.0.2 on 2026-02-16 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_cobrado_por_to_cuota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='cobrador',
            field=models.ForeignKey(blank=True, help_text='Usuario/cobrador que creó y gestiona este préstamo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Cobrador'),
        ),
    ]
