# Generated by Django 6.0.2 on 2026-02-17 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_populate_prestamo_cobrador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialModificacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Modificación')),
                ('tipo_modificacion', models.CharField(choices=[('PP', 'Pago Parcial'), ('PA', 'Pago Completo'), ('TR', 'Restante a Próxima Cuota'), ('CE', 'Cuota Especial Creada'), ('MR', 'Monto Recibido de Otra Cuota')], max_length=2, verbose_name='Tipo de Modificación')),
                ('monto_cuota_anterior', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Cuota Anterior')),
                ('monto_cuota_nuevo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Cuota Nuevo')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Pagado')),
                ('monto_restante_transferido', models.DecimalField(decimal_places=2, default=0, help_text='Monto que se transfirió a otra cuota', max_digits=12, verbose_name='Monto Restante Transferido')),
                ('interes_mora', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Interés por Mora')),
                ('metodo_pago', models.CharField(blank=True, default='', max_length=2, verbose_name='Método de Pago')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_modificaciones', to='core.cuota', verbose_name='Cuota')),
                ('cuota_relacionada', models.ForeignKey(blank=True, help_text='Cuota origen o destino de la transferencia de monto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_relacionadas', to='core.cuota', verbose_name='Cuota Relacionada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Modificación de Pago',
                'verbose_name_plural': 'Historial de Modificaciones de Pago',
                'ordering': ['-fecha_modificacion'],
                'indexes': [models.Index(fields=['-fecha_modificacion'], name='core_histor_fecha_m_27bb57_idx'), models.Index(fields=['cuota'], name='core_histor_cuota_i_3dd325_idx'), models.Index(fields=['tipo_modificacion'], name='core_histor_tipo_mo_147857_idx')],
            },
        ),
    ]
