# Generated by Django 4.2.27 on 2026-02-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_historialmodificacionpago'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_finalizacion_manual',
            field=models.BooleanField(default=False, help_text='Indica si la fecha fue establecida manualmente', verbose_name='Fecha de finalización manual'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, help_text='Dejar vacío para calcular automáticamente según frecuencia y cuotas', null=True, verbose_name='Fecha de Finalización'),
        ),
    ]
