# Generated by Django 4.2.30 on 2026-08-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Sincroniza el estado de migraciones con las choices de tipo_modificacion
    ya presentes en el modelo (drift preexistente, no relacionado a esta rama).
    No cambia el tipo de columna ni requiere backfill de datos.
    """

    dependencies = [
        ('core', '0014_add_fecha_finalizacion_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmodificacionpago',
            name='tipo_modificacion',
            field=models.CharField(choices=[('PP', 'Pago Parcial'), ('PA', 'Pago Completo'), ('TR', 'Restante a Próxima Cuota'), ('CE', 'Cuota Especial Creada'), ('MR', 'Monto Recibido de Otra Cuota'), ('AN', 'Pago Anulado')], max_length=2, verbose_name='Tipo de Modificación'),
        ),
    ]
