# Generated by Django 4.2.27 on 2026-02-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_fecha_finalizacion_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento Nacional de Identidad', max_length=20, null=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia1_nombre',
            field=models.CharField(blank=True, help_text='Nombre y parentesco del contacto de referencia', max_length=200, null=True, verbose_name='Referencia 1 - Nombre/Parentesco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia1_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Referencia 1 - Teléfono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia2_nombre',
            field=models.CharField(blank=True, help_text='Nombre y parentesco del contacto de referencia', max_length=200, null=True, verbose_name='Referencia 2 - Nombre/Parentesco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia2_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Referencia 2 - Teléfono'),
        ),
        migrations.AlterField(
            model_name='historialmodificacionpago',
            name='tipo_modificacion',
            field=models.CharField(choices=[('PP', 'Pago Parcial'), ('PA', 'Pago Completo'), ('TR', 'Restante a Próxima Cuota'), ('CE', 'Cuota Especial Creada'), ('MR', 'Monto Recibido de Otra Cuota'), ('AN', 'Pago Anulado')], max_length=2, verbose_name='Tipo de Modificación'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='frecuencia',
            field=models.CharField(choices=[('DI', 'Diario'), ('SE', 'Semanal'), ('QU', 'Quincenal'), ('ME', 'Mensual'), ('PU', 'Pago Único')], default='DI', max_length=2, verbose_name='Frecuencia de Pago'),
        ),
    ]
