# Generated by Django 4.2.27 on 2026-02-23 04:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_dni_referencias_pago_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Máximo que se le puede prestar. 0 = sin límite (ilimitado)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Límite de Crédito'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tasa_interes_porcentaje',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de interés sobre el capital. Ej: 20 = 20%', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tasa de Interés (%)'),
        ),
    ]
