# Generated by Django 4.2.30 on 2026-08-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_configuracioncategorizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, help_text='Activar recién cuando el número ya esté verificado en Meta y la plantilla aprobada. Mientras esté apagado, los comandos de envío no hacen nada.', verbose_name='WhatsApp activo')),
                ('template_recordatorio', models.CharField(default='recordatorio_cuota', help_text='Debe coincidir exactamente con el nombre de la plantilla ya aprobada en Meta', max_length=100, verbose_name='Nombre de la plantilla (recordatorio B1)')),
                ('idioma_plantillas', models.CharField(default='es_AR', max_length=10, verbose_name='Idioma de las plantillas')),
                ('hora_envio_recordatorio', models.TimeField(default='10:00', help_text='Informativo: el horario real lo define el Cron Job en Railway, esto es solo para referencia', verbose_name='Hora de envío del recordatorio')),
            ],
            options={
                'verbose_name': 'Configuración de WhatsApp',
                'verbose_name_plural': 'Configuración de WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='EnvioWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RE', 'Recordatorio de cuota (B1)')], max_length=2, verbose_name='Tipo')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('exitoso', models.BooleanField(default=False, verbose_name='Exitoso')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Error')),
                ('message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de mensaje (Meta)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_whatsapp', to='core.cliente', verbose_name='Cliente')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_whatsapp', to='core.cuota', verbose_name='Cuota')),
            ],
            options={
                'verbose_name': 'Envío de WhatsApp',
                'verbose_name_plural': 'Envíos de WhatsApp',
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['cuota', 'tipo', 'fecha_envio'], name='core_enviow_cuota_i_e69b61_idx')],
            },
        ),
    ]
