# Generated by Django 4.2.27 on 2026-03-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_historialmodificacionpago_tipo_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmodificacionpago',
            name='tipo_modificacion',
            field=models.CharField(choices=[('PP', 'Pago Parcial'), ('PA', 'Pago Completo'), ('TR', 'Restante a Próxima Cuota'), ('CE', 'Cuota Especial Creada'), ('MR', 'Monto Recibido de Otra Cuota'), ('AN', 'Pago Anulado'), ('ED', 'Cobro Editado'), ('RM', 'Registro de Mora')], max_length=2, verbose_name='Tipo de Modificación'),
        ),
    ]
