# Generated by Django 4.2.27 on 2026-04-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_registro_mora_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], db_index=True, default='AC', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado'), ('PC', 'Pago Parcial')], db_index=True, default='PE', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_vencimiento',
            field=models.DateField(db_index=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('AC', 'Activo'), ('FI', 'Finalizado'), ('CA', 'Cancelado'), ('RE', 'Renovado')], db_index=True, default='AC', max_length=2, verbose_name='Estado'),
        ),
    ]
