# Generated by Django 4.2.27 on 2026-04-14 05:31

from django.db import migrations, models
import uuid


def generar_uuids_existentes(apps, schema_editor):
    """Genera UUIDs únicos para préstamos existentes"""
    Prestamo = apps.get_model('core', 'Prestamo')
    for prestamo in Prestamo.objects.all():
        prestamo.token_publico = uuid.uuid4()
        prestamo.save(update_fields=['token_publico'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_db_indexes'),
    ]

    operations = [
        # Paso 1: Agregar token_activo (simple, con default)
        migrations.AddField(
            model_name='prestamo',
            name='token_activo',
            field=models.BooleanField(default=True, verbose_name='Link Público Activo'),
        ),
        # Paso 2: Agregar token_publico SIN unique (para poder poblar)
        migrations.AddField(
            model_name='prestamo',
            name='token_publico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Token Público'),
        ),
        # Paso 3: Poblar UUIDs únicos en registros existentes
        migrations.RunPython(generar_uuids_existentes, migrations.RunPython.noop),
        # Paso 4: Hacer el campo NOT NULL + unique + db_index
        migrations.AlterField(
            model_name='prestamo',
            name='token_publico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, db_index=True, verbose_name='Token Público'),
        ),
    ]
