# Generated by Django 4.2.30 on 2026-08-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_token_publico_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCategorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorizacion_automatica', models.BooleanField(default=False, help_text='Si está activo, el sistema recalcula la categoría del cliente solo al finalizar cada préstamo. Si está apagado (por defecto), la categoría la definen manualmente el admin o el cobrador.', verbose_name='Categorización automática')),
            ],
            options={
                'verbose_name': 'Configuración de Categorización',
                'verbose_name_plural': 'Configuración de Categorización',
            },
        ),
    ]
