# Generated by Django 4.2.30 on 2026-08-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_configuracionwhatsapp_enviowhatsapp'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='core_cuota_estado_e94d11_idx'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['fecha_pago_real'], name='core_cuota_fecha_p_65c52b_idx'),
        ),
    ]
