# Generated by Django 4.2.30 on 2026-08-21 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_add_token_publico_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=280, verbose_name='Nota')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Vacío = no vence sola, hay que borrarla a mano', null=True, verbose_name='Vence el')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_seguimiento', to='core.prestamo', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Nota de Seguimiento',
                'verbose_name_plural': 'Notas de Seguimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
