# Generated by Django 4.2.30 on 2026-09-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_notaseguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('AC', 'Activo'), ('FI', 'Finalizado'), ('CA', 'Cancelado'), ('RE', 'Renovado'), ('IR', 'Irrecuperable')], db_index=True, default='AC', max_length=2, verbose_name='Estado'),
        ),
    ]
