# Generated by Django 4.2.30 on 2026-09-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_prestamo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMoraReciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_corte', models.PositiveIntegerField(default=7, help_text='Cuotas vencidas hace hasta esta cantidad de días se muestran en "Mora Reciente". Más allá de este corte, pasan a "Vencidas".', verbose_name='Días de corte para "Mora reciente"')),
            ],
            options={
                'verbose_name': 'Configuración de Mora Reciente',
                'verbose_name_plural': 'Configuración de Mora Reciente',
            },
        ),
    ]
