# Generated by Django 4.2.30 on 2026-09-13 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_configuracionmorareciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMensajesAutomaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, help_text='Interruptor general. Mientras esté apagado, el comando de envío no hace nada.', verbose_name='Mensajes automáticos activos')),
                ('confirmado_en', models.DateTimeField(blank=True, help_text='Cuándo se aceptó por primera vez el envío automático de estos mensajes a los clientes.', null=True, verbose_name='Confirmado el')),
                ('recordatorio_activo', models.BooleanField(default=True, verbose_name='Recordatorio preventivo activo')),
                ('recordatorio_dias_antes', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Días antes del vencimiento')),
                ('recordatorio_hora', models.TimeField(default='09:00', verbose_name='Hora de envío')),
                ('recordatorio_dias_semana', models.CharField(blank=True, default='LMXJVS', help_text='Letras de DIAS_SEMANA_CODIGOS (L M X J V S D) presentes en el string cuentan como activas.', max_length=7, verbose_name='Días activos')),
                ('recordatorio_plantilla', models.TextField(default='Hola {{nombre}} 👋 Te recordamos que el {{fecha_vencimiento}} vence tu cuota de {{monto}}. ¡Gracias por tu pago puntual!', help_text='Variables disponibles: {{nombre}}, {{monto}}, {{fecha_vencimiento}}', verbose_name='Texto del mensaje')),
                ('aviso_dia_activo', models.BooleanField(default=True, verbose_name='Aviso del día activo')),
                ('aviso_dia_hora', models.TimeField(default='09:00', verbose_name='Hora de envío')),
                ('aviso_dia_dias_semana', models.CharField(blank=True, default='LMXJVS', max_length=7, verbose_name='Días activos')),
                ('aviso_dia_plantilla', models.TextField(default='Hola {{nombre}}, hoy vence tu cuota de {{monto}}. Podés abonarla con tu cobrador o por transferencia. ¡Te esperamos!', help_text='Variables disponibles: {{nombre}}, {{monto}}, {{fecha_vencimiento}}', verbose_name='Texto del mensaje')),
                ('aviso_mora_activo', models.BooleanField(default=True, verbose_name='Aviso de mora activo')),
                ('aviso_mora_dias_despues', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Días después del vencimiento')),
                ('aviso_mora_hora', models.TimeField(default='09:00', verbose_name='Hora de envío')),
                ('aviso_mora_dias_semana', models.CharField(blank=True, default='LMXJV', max_length=7, verbose_name='Días activos')),
                ('aviso_mora_plantilla', models.TextField(default='Hola {{nombre}}, notamos que tu cuota de {{monto}} venció el {{fecha_vencimiento}} y todavía no la registramos. Por favor comunicate para regularizar tu situación.', help_text='Variables disponibles: {{nombre}}, {{monto}}, {{fecha_vencimiento}}', verbose_name='Texto del mensaje')),
            ],
            options={
                'verbose_name': 'Configuración de Mensajes Automáticos',
                'verbose_name_plural': 'Configuración de Mensajes Automáticos',
            },
        ),
        migrations.AddField(
            model_name='enviowhatsapp',
            name='canal',
            field=models.CharField(choices=[('MC', 'API oficial de Meta'), ('QR', 'Número personal (QR)')], default='MC', help_text='Por cuál de los dos caminos de WhatsApp se mandó (no se mezclan entre sí)', max_length=2, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='enviowhatsapp',
            name='tipo',
            field=models.CharField(choices=[('RE', 'Recordatorio de cuota (B1)'), ('RP', 'Recordatorio preventivo (antes del vencimiento)'), ('AD', 'Aviso el día del vencimiento'), ('AM', 'Aviso de mora (después del vencimiento)')], max_length=2, verbose_name='Tipo'),
        ),
    ]
