# Generated by Django 4.2.30 on 2026-09-16 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_configuracionmensajesautomaticos_enviowhatsapp_canal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=280, verbose_name='Tarea')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_pendientes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tarea Pendiente',
                'verbose_name_plural': 'Tareas Pendientes',
                'ordering': ['completada', '-fecha_creacion'],
            },
        ),
    ]
