# Generated by Django 4.2.30 on 2026-09-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tareapendiente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareapendiente',
            options={'ordering': ['completada', 'orden', '-fecha_creacion'], 'verbose_name': 'Tarea Pendiente', 'verbose_name_plural': 'Tareas Pendientes'},
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_vinculadas', to='core.cliente', verbose_name='Cliente vinculado'),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_vinculadas', to='core.cuota', verbose_name='Cuota vinculada'),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Vence el'),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden manual (arrastrar en el widget)', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_vinculadas', to='core.prestamo', verbose_name='Préstamo vinculado'),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='prioridad',
            field=models.CharField(choices=[('AL', 'Alta'), ('ME', 'Media'), ('BA', 'Baja')], default='ME', max_length=2, verbose_name='Prioridad'),
        ),
    ]
