# Generated by Django 4.2.30 on 2026-09-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_tareapendiente_options_tareapendiente_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmensajesautomaticos',
            name='alias_pago',
            field=models.CharField(blank=True, help_text='Se usa para reemplazar {{alias}} en los textos de los mensajes.', max_length=100, verbose_name='Alias para pagos por transferencia'),
        ),
        migrations.AlterField(
            model_name='configuracionmensajesautomaticos',
            name='aviso_dia_plantilla',
            field=models.TextField(default='Hola {{nombre}}, te recuerdo que hoy vence tu cuota de {{monto}}. Te dejo el alias: {{alias}}. ¡Gracias!', help_text='Variables disponibles: {{nombre}}, {{monto}}, {{fecha_vencimiento}}, {{alias}}', verbose_name='Texto del mensaje'),
        ),
        migrations.AlterField(
            model_name='configuracionmensajesautomaticos',
            name='aviso_mora_plantilla',
            field=models.TextField(default='Hola {{nombre}}, notamos que tu cuota de {{monto}} venció el {{fecha_vencimiento}} y todavía no la registramos. Por favor comunicate para regularizar tu situación.', help_text='Variables disponibles: {{nombre}}, {{monto}}, {{fecha_vencimiento}}, {{alias}}', verbose_name='Texto del mensaje'),
        ),
        migrations.AlterField(
            model_name='configuracionmensajesautomaticos',
            name='recordatorio_plantilla',
            field=models.TextField(default='Hola {{nombre}} 👋 Te recordamos que el {{fecha_vencimiento}} vence tu cuota de {{monto}}. ¡Gracias por tu pago puntual!', help_text='Variables disponibles: {{nombre}}, {{monto}}, {{fecha_vencimiento}}, {{alias}}', verbose_name='Texto del mensaje'),
        ),
    ]
