# Generated by Django 4.2.30 on 2026-09-26 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_configuracionmensajesautomaticos_alias_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='CONTRATO DE MUTUO', max_length=200, verbose_name='Título del contrato')),
                ('cuerpo', models.TextField(default='Entre {{cliente_nombre}}, DNI {{cliente_dni}}, con domicilio en {{cliente_direccion}}, en adelante "EL DEUDOR", y la parte prestamista, en adelante "EL ACREEDOR", se celebra el presente contrato de mutuo, sujeto a las siguientes cláusulas:\n\nPRIMERA: EL ACREEDOR entrega en préstamo a EL DEUDOR la suma de {{monto_solicitado}}, que EL DEUDOR declara recibir en este acto de plena conformidad.\n\nSEGUNDA: EL DEUDOR se compromete a devolver la suma total de {{monto_total}}, en {{cuotas_pactadas}} cuotas de frecuencia {{frecuencia}}, comenzando el {{fecha_inicio}} y finalizando el {{fecha_finalizacion}}.\n\nTERCERA: La tasa de interés pactada es del {{tasa_interes}}% sobre el capital solicitado.\n\nCUARTA: El incumplimiento en el pago de una o más cuotas en su fecha de vencimiento generará los recargos por mora que EL ACREEDOR informe oportunamente a EL DEUDOR.\n\nQUINTA: Para todos los efectos del presente contrato, las partes se someten a la jurisdicción de los tribunales ordinarios competentes.\n\nEn prueba de conformidad, se firma el presente contrato en el día de la fecha, {{fecha_hoy}}.', help_text='Variables disponibles: {{cliente_nombre}}, {{cliente_dni}}, {{cliente_direccion}}, {{monto_solicitado}}, {{monto_total}}, {{cuotas_pactadas}}, {{frecuencia}}, {{tasa_interes}}, {{fecha_inicio}}, {{fecha_finalizacion}}, {{fecha_hoy}}', verbose_name='Texto del contrato')),
            ],
            options={
                'verbose_name': 'Configuración de Contrato',
                'verbose_name_plural': 'Configuración de Contrato',
            },
        ),
        migrations.CreateModel(
            name='FirmaPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_imagen_base64', models.TextField(verbose_name='Firma (imagen)')),
                ('hash_pdf', models.CharField(max_length=64, verbose_name='Hash SHA-256 del PDF firmado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Navegador/Dispositivo')),
                ('firmado_en', models.DateTimeField(auto_now_add=True, verbose_name='Firmado el')),
                ('firmado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma', to='core.prestamo', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Firma de Contrato',
                'verbose_name_plural': 'Firmas de Contrato',
            },
        ),
    ]
